const mongoose  = require("mongoose");

// const deviceSchema = mongoose.Schema({
//     title:String,
//     category:String,
//     brand:String,
//     price:Object,
//     colours:Object,
//     availability:Object,
//     images:Array,
//     videos:Array,
//     family:Array,
//     dimensions:String,
//     weight:String,
//     build:String,
//     cpu:String,
//     cpuspeed:String,
//     cpucores:String,
//     s2bratio:String,
//     displaytype:String,
//     displaysize:String,
//     displayprotection:String,
//     colordepth:String,
//     brightness:String,
//     refreshrate:String,
//     displayresolution:String,
//     displayfeatures:String,
//     ram:String,
//     ramtype:String,
//     ramexpansion:String,
//     storage:String,
//     storagetype:String,
//     storageexpansion:String,
//     numberofcameras:Number,
//     cameras:Array,
//     numberofsim:String,
//     simsize:String,
//     bands:Array,
//     networks:Array,
//     usbinterface:String,
//     usbversion:String,
//     earjack:String,
//     wifi:String,
//     bluetooth:String,
//     connectivity:String,
//     os:String,
//     sensors:Array,
//     dimensions:String,
//     battery:Object,
//     charging:String,
//     audiovideo:Object,
//     servicesandapplications:Object,
//     manufacturerinfo:Object,
// })

const deviceSchema = mongoose.Schema({
    title:String,
    category:String,
    brand:String,
    price:Object,
    colors:Object,
    images:Array,
    family:Array,
    body:Array,
    display:Array,
    platform:Array,
    memory:Array,
    maincamera:Object,
    selfiecamera:Object,
    sound:Array,
    communication:Object,
    features:Array,
    sensors:Array,
    battery:Array,
    misc:Array,
    package:Array,
    highlights:Array,
    filter:{
        brand:{type:String, default:""},
        range:{type:String, default:""},
        category:{type:Array, default:[]},
        processor:{type:String, default:""},
        ram:{type:Array, default:[]},
        storage:{type:Array, default:[]},
        display_type:{type:String, default:""},
        display_size:{type:String, default:""}
    }
})


const deviceModel = mongoose.model("devices",deviceSchema);

module.exports = {
    deviceModel
}